/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DemoRoot {
    }
    interface FormOne {
    }
}
declare global {
    interface HTMLDemoRootElement extends Components.DemoRoot, HTMLStencilElement {
    }
    var HTMLDemoRootElement: {
        prototype: HTMLDemoRootElement;
        new (): HTMLDemoRootElement;
    };
    interface HTMLFormOneElement extends Components.FormOne, HTMLStencilElement {
    }
    var HTMLFormOneElement: {
        prototype: HTMLFormOneElement;
        new (): HTMLFormOneElement;
    };
    interface HTMLElementTagNameMap {
        "demo-root": HTMLDemoRootElement;
        "form-one": HTMLFormOneElement;
    }
}
declare namespace LocalJSX {
    interface DemoRoot {
    }
    interface FormOne {
    }
    interface IntrinsicElements {
        "demo-root": DemoRoot;
        "form-one": FormOne;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "demo-root": LocalJSX.DemoRoot & JSXBase.HTMLAttributes<HTMLDemoRootElement>;
            "form-one": LocalJSX.FormOne & JSXBase.HTMLAttributes<HTMLFormOneElement>;
        }
    }
}
