compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

supportedArchitectures:
    cpu:
        - current
        - arm64
        - x64
    os:
        - current
        - darwin
        - linux
        - win32

yarnPath: .yarn/releases/yarn-4.0.1.cjs
