nodeLinker: node-modules

npmScopes:
  eventstore:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.1.0.cjs

changesetBaseRefs: 
  - 632d8acf95e8008f8b678b7e9b5c151eb6546f8e