/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IconDescription } from "@eventstore-ui/components";
import { FieldChange, RenderFunction, ValidationMessages } from "./types";
import { MaskOptions } from "./components/es-input/types";
import { OptionFilter, RenderTypeaheadField, RenderTypeaheadOption, TypeaheadOption } from "./components/es-typeahead/types";
import { RadioCardGroupOption, RenderCard } from "./components/es-radio-card-group/types";
import { RenderSelectValue } from "./components/es-select/types";
export { IconDescription } from "@eventstore-ui/components";
export { FieldChange, RenderFunction, ValidationMessages } from "./types";
export { MaskOptions } from "./components/es-input/types";
export { OptionFilter, RenderTypeaheadField, RenderTypeaheadOption, TypeaheadOption } from "./components/es-typeahead/types";
export { RadioCardGroupOption, RenderCard } from "./components/es-radio-card-group/types";
export { RenderSelectValue } from "./components/es-select/types";
export namespace Components {
    /**
     * A checkbox component
     */
    interface EsCheckbox {
        /**
          * If the field is disabled.
         */
        "disabled"?: boolean;
        /**
          * The icon to use.
         */
        "icon": IconDescription;
        /**
          * If the field is currently in an error state.
         */
        "invalid"?: boolean;
        /**
          * The name of the field.
         */
        "name": string;
        /**
          * If the field is editable.
         */
        "readonly"?: boolean;
        /**
          * The current value of the field.
         */
        "value": boolean;
    }
    /**
     * An optionally masked text input.
     */
    interface EsInput {
        /**
          * If the field is disabled.
         */
        "disabled"?: boolean;
        /**
          * Pass props directly to the input.
         */
        "inputProps"?: Record<string, any>;
        /**
          * If the field is currently in an error state.
         */
        "invalid"?: boolean;
        /**
          * The label of the field.
         */
        "label": string;
        /**
          * Apply an input mask
         */
        "mask"?: MaskOptions;
        /**
          * The validation messages of the field
         */
        "messages"?: ValidationMessages;
        /**
          * The name of the field.
         */
        "name": string;
        /**
          * The placeholder for the input.
         */
        "placeholder": string;
        /**
          * If the field is editable.
         */
        "readonly"?: boolean;
        /**
          * The current value of the field.
         */
        "value": string;
    }
    /**
     * A list creator input.
     */
    interface EsInputList {
        /**
          * Icon for the add item button.
         */
        "additionIcon": IconDescription;
        /**
          * Text for the add item button.
         */
        "additionText": string;
        /**
          * Icon for the delete button.
         */
        "deleteIcon": IconDescription;
        /**
          * If the input is disabled.
         */
        "disabled"?: boolean;
        /**
          * The label of the field.
         */
        "label": string;
        /**
          * The validation messages of the field
         */
        "messages"?: ValidationMessages;
        /**
          * The name of the field.
         */
        "name": string;
        /**
          * Display a placeholder in the input.
         */
        "placeholder": string;
        /**
          * The currently selected values
         */
        "value": string[];
    }
    /**
     * A list creator input.
     */
    interface EsListCreator {
        /**
          * The icon to display next to the field
         */
        "addIcon": IconDescription;
        /**
          * Icon for the delete button.
         */
        "deleteIcon": IconDescription;
        /**
          * If the field is disabled.
         */
        "disabled"?: boolean;
        /**
          * The icon to display next to the field
         */
        "icon"?: IconDescription;
        /**
          * The label of the field.
         */
        "label": string;
        /**
          * The validation messages of the field
         */
        "messages"?: ValidationMessages;
        /**
          * The name of the field.
         */
        "name": string;
        /**
          * A list of options to choose from.
         */
        "options": TypeaheadOption[];
        /**
          * The placeholder for the input.
         */
        "placeholder": string;
        /**
          * Render the list item.
         */
        "renderItem": RenderFunction<[option: TypeaheadOption]>;
        /**
          * The selected item ids
         */
        "value": string[];
    }
    /**
     * An extra large input.
     */
    interface EsMegaInput {
        /**
          * If the field is disabled.
         */
        "disabled"?: boolean;
        /**
          * Pass props directly to the input.
         */
        "inputProps"?: Record<string, any>;
        /**
          * If the field is currently in an error state.
         */
        "invalid"?: boolean;
        /**
          * The label of the field.
         */
        "label": string;
        /**
          * The validation messages of the field
         */
        "messages"?: ValidationMessages;
        /**
          * The name of the field.
         */
        "name": string;
        /**
          * The placeholder for the input.
         */
        "placeholder": string;
        /**
          * If the field is editable.
         */
        "readonly"?: boolean;
        /**
          * The current value of the field.
         */
        "value": string;
    }
    /**
     * A number based input. Values should be passed around as strings, as numbers can round / floating point / overflow etc if a number type is used.
     */
    interface EsNumberInput {
        /**
          * If the field is disabled.
         */
        "disabled"?: boolean;
        /**
          * Pass props directly to the input.
         */
        "inputProps"?: Record<string, any>;
        /**
          * If the field is currently in an error state.
         */
        "invalid"?: boolean;
        /**
          * The label of the field.
         */
        "label": string;
        /**
          * The validation messages of the field
         */
        "messages"?: ValidationMessages;
        /**
          * The name of the field.
         */
        "name": string;
        /**
          * The placeholder for the input.
         */
        "placeholder"?: string;
        /**
          * If the field is editable.
         */
        "readonly"?: boolean;
        /**
          * Display a unit beside the input.
         */
        "unit"?: string;
        /**
          * The current value of the field.
         */
        "value": string;
    }
    /**
     * A card based single select input.
     */
    interface EsRadioCardGroup {
        /**
          * Group the cards by a key.
         */
        "groupBy"?: string;
        /**
          * Icon to display when checked.
         */
        "icon": IconDescription;
        /**
          * If the field is currently in an error state.
         */
        "invalid": boolean;
        /**
          * The id of the component that labels this input. This input doesn't bring its own label, so must be labeled externally and referenced here.
         */
        "labelledby": string;
        /**
          * The validation messages of the field
         */
        "messages"?: ValidationMessages;
        /**
          * The name of the field.
         */
        "name": string;
        /**
          * The options to be displayed and chosen from.
         */
        "options": RadioCardGroupOption[];
        /**
          * Overwrite the default card renderer
         */
        "renderCard": RenderCard<any>;
        /**
          * The current value of the field.
         */
        "value": string | null;
    }
    /**
     * A searchable select dropdown.
     */
    interface EsSelect {
        /**
          * Icon to use as a chevron.
         */
        "chevronIcon": IconDescription;
        /**
          * If the field is disabled.
         */
        "disabled"?: boolean;
        /**
          * Pass props directly to the input.
         */
        "inputProps"?: Record<string, any>;
        /**
          * If the field is currently in an error state.
         */
        "invalid"?: boolean;
        /**
          * The label of the field.
         */
        "label": string;
        /**
          * The validation messages of the field
         */
        "messages"?: ValidationMessages;
        /**
          * The name of the field.
         */
        "name": string;
        /**
          * Pass a custom search filter function
         */
        "optionFilter"?: OptionFilter;
        /**
          * A list of options to choose from.
         */
        "options": TypeaheadOption[];
        /**
          * The placeholder for the input.
         */
        "placeholder"?: string;
        /**
          * If the field is editable.
         */
        "readonly"?: boolean;
        /**
          * Overwrite the default option renderer.
         */
        "renderOption"?: RenderTypeaheadOption<any>;
        /**
          * Overwrite the default value renderer.
         */
        "renderValue": RenderSelectValue<any>;
        /**
          * The current value of the field.
         */
        "value": string | null;
    }
    /**
     * A switchable switch.
     */
    interface EsSwitch {
        /**
          * Icon to display when switch is on in high contrast mode.
         */
        "activeIcon": IconDescription;
        /**
          * Text to display when switch is on in high contrast mode.
         */
        "activeText": string;
        /**
          * If the field is disabled.
         */
        "disabled"?: boolean;
        /**
          * Icon to display when switch is off in high contrast mode.
         */
        "inactiveIcon": IconDescription;
        /**
          * Text to display when switch is off in high contrast mode.
         */
        "inactiveText": string;
        /**
          * If the field is currently in an error state.
         */
        "invalid"?: boolean;
        /**
          * The name of the field.
         */
        "name": string;
        /**
          * If the field is editable.
         */
        "readonly"?: boolean;
        /**
          * Allows you to pause interaction with the input while an operation completes.
         */
        "setPending": (pending: boolean) => Promise<void>;
        /**
          * The current value of the field.
         */
        "value": boolean;
    }
    /**
     * A switchable switch field.
     */
    interface EsSwitchField {
        /**
          * Icon to display when switch is on in high contrast mode.
         */
        "activeIcon"?: IconDescription;
        /**
          * Text to display when switch is on in high contrast mode.
         */
        "activeText"?: string;
        /**
          * If the field is disabled.
         */
        "disabled"?: boolean;
        /**
          * Icon to display when switch is off in high contrast mode.
         */
        "inactiveIcon"?: IconDescription;
        /**
          * Text to display when switch is off in high contrast mode.
         */
        "inactiveText"?: string;
        /**
          * If the field is currently in an error state.
         */
        "invalid"?: boolean;
        /**
          * The label of the field.
         */
        "label": string;
        /**
          * The validation messages of the field
         */
        "messages"?: ValidationMessages;
        /**
          * The name of the field.
         */
        "name": string;
        /**
          * If the field is editable.
         */
        "readonly"?: boolean;
        /**
          * Allows you to pause interaction with the input while an operation completes.
         */
        "setPending": (pending: boolean) => Promise<void>;
        /**
          * The current value of the field.
         */
        "value": boolean;
    }
    /**
     * A textarea field.
     */
    interface EsTextarea {
        /**
          * If the field is disabled.
         */
        "disabled"?: boolean;
        /**
          * Pass props directly to the input.
         */
        "inputProps"?: Record<string, any>;
        /**
          * If the field is currently in an error state.
         */
        "invalid"?: boolean;
        /**
          * The label of the field.
         */
        "label": string;
        /**
          * The validation messages of the field
         */
        "messages"?: ValidationMessages;
        /**
          * The name of the field.
         */
        "name": string;
        /**
          * The placeholder for the input.
         */
        "placeholder": string;
        /**
          * If the field is editable.
         */
        "readonly"?: boolean;
        /**
          * The current value of the field.
         */
        "value": string;
    }
    interface EsTypeahead {
        "clearOnSelect": boolean;
        "closeOnSelect": boolean;
        "disabled"?: boolean;
        "name": string;
        "optionFilter": OptionFilter;
        "options": TypeaheadOption[];
        "readonly"?: boolean;
        "renderField": RenderTypeaheadField;
        "renderOption": RenderTypeaheadOption;
        "value": string[];
        "zIndex": number;
    }
    /**
     * Display messages under fields.
     */
    interface EsValidationMessages {
        /**
          * Icon to diplay next to errors. (if `showIcons` or high contrast)
         */
        "errorIcon": IconDescription;
        /**
          * Icon to diplay next to infos. (if `showIcons` or high contrast)
         */
        "infoIcon": IconDescription;
        /**
          * The messages to display.
         */
        "messages"?: Partial<ValidationMessages>;
        /**
          * Display icons alongside messages.
         */
        "showIcons": boolean;
        /**
          * Icon to diplay next to warnings. (if `showIcons` or high contrast)
         */
        "warningIcon": IconDescription;
    }
}
export interface EsCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEsCheckboxElement;
}
export interface EsInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEsInputElement;
}
export interface EsInputListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEsInputListElement;
}
export interface EsListCreatorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEsListCreatorElement;
}
export interface EsMegaInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEsMegaInputElement;
}
export interface EsNumberInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEsNumberInputElement;
}
export interface EsRadioCardGroupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEsRadioCardGroupElement;
}
export interface EsSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEsSelectElement;
}
export interface EsSwitchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEsSwitchElement;
}
export interface EsSwitchFieldCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEsSwitchFieldElement;
}
export interface EsTextareaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEsTextareaElement;
}
export interface EsTypeaheadCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEsTypeaheadElement;
}
declare global {
    /**
     * A checkbox component
     */
    interface HTMLEsCheckboxElement extends Components.EsCheckbox, HTMLStencilElement {
    }
    var HTMLEsCheckboxElement: {
        prototype: HTMLEsCheckboxElement;
        new (): HTMLEsCheckboxElement;
    };
    /**
     * An optionally masked text input.
     */
    interface HTMLEsInputElement extends Components.EsInput, HTMLStencilElement {
    }
    var HTMLEsInputElement: {
        prototype: HTMLEsInputElement;
        new (): HTMLEsInputElement;
    };
    /**
     * A list creator input.
     */
    interface HTMLEsInputListElement extends Components.EsInputList, HTMLStencilElement {
    }
    var HTMLEsInputListElement: {
        prototype: HTMLEsInputListElement;
        new (): HTMLEsInputListElement;
    };
    /**
     * A list creator input.
     */
    interface HTMLEsListCreatorElement extends Components.EsListCreator, HTMLStencilElement {
    }
    var HTMLEsListCreatorElement: {
        prototype: HTMLEsListCreatorElement;
        new (): HTMLEsListCreatorElement;
    };
    /**
     * An extra large input.
     */
    interface HTMLEsMegaInputElement extends Components.EsMegaInput, HTMLStencilElement {
    }
    var HTMLEsMegaInputElement: {
        prototype: HTMLEsMegaInputElement;
        new (): HTMLEsMegaInputElement;
    };
    /**
     * A number based input. Values should be passed around as strings, as numbers can round / floating point / overflow etc if a number type is used.
     */
    interface HTMLEsNumberInputElement extends Components.EsNumberInput, HTMLStencilElement {
    }
    var HTMLEsNumberInputElement: {
        prototype: HTMLEsNumberInputElement;
        new (): HTMLEsNumberInputElement;
    };
    /**
     * A card based single select input.
     */
    interface HTMLEsRadioCardGroupElement extends Components.EsRadioCardGroup, HTMLStencilElement {
    }
    var HTMLEsRadioCardGroupElement: {
        prototype: HTMLEsRadioCardGroupElement;
        new (): HTMLEsRadioCardGroupElement;
    };
    /**
     * A searchable select dropdown.
     */
    interface HTMLEsSelectElement extends Components.EsSelect, HTMLStencilElement {
    }
    var HTMLEsSelectElement: {
        prototype: HTMLEsSelectElement;
        new (): HTMLEsSelectElement;
    };
    /**
     * A switchable switch.
     */
    interface HTMLEsSwitchElement extends Components.EsSwitch, HTMLStencilElement {
    }
    var HTMLEsSwitchElement: {
        prototype: HTMLEsSwitchElement;
        new (): HTMLEsSwitchElement;
    };
    /**
     * A switchable switch field.
     */
    interface HTMLEsSwitchFieldElement extends Components.EsSwitchField, HTMLStencilElement {
    }
    var HTMLEsSwitchFieldElement: {
        prototype: HTMLEsSwitchFieldElement;
        new (): HTMLEsSwitchFieldElement;
    };
    /**
     * A textarea field.
     */
    interface HTMLEsTextareaElement extends Components.EsTextarea, HTMLStencilElement {
    }
    var HTMLEsTextareaElement: {
        prototype: HTMLEsTextareaElement;
        new (): HTMLEsTextareaElement;
    };
    interface HTMLEsTypeaheadElement extends Components.EsTypeahead, HTMLStencilElement {
    }
    var HTMLEsTypeaheadElement: {
        prototype: HTMLEsTypeaheadElement;
        new (): HTMLEsTypeaheadElement;
    };
    /**
     * Display messages under fields.
     */
    interface HTMLEsValidationMessagesElement extends Components.EsValidationMessages, HTMLStencilElement {
    }
    var HTMLEsValidationMessagesElement: {
        prototype: HTMLEsValidationMessagesElement;
        new (): HTMLEsValidationMessagesElement;
    };
    interface HTMLElementTagNameMap {
        "es-checkbox": HTMLEsCheckboxElement;
        "es-input": HTMLEsInputElement;
        "es-input-list": HTMLEsInputListElement;
        "es-list-creator": HTMLEsListCreatorElement;
        "es-mega-input": HTMLEsMegaInputElement;
        "es-number-input": HTMLEsNumberInputElement;
        "es-radio-card-group": HTMLEsRadioCardGroupElement;
        "es-select": HTMLEsSelectElement;
        "es-switch": HTMLEsSwitchElement;
        "es-switch-field": HTMLEsSwitchFieldElement;
        "es-textarea": HTMLEsTextareaElement;
        "es-typeahead": HTMLEsTypeaheadElement;
        "es-validation-messages": HTMLEsValidationMessagesElement;
    }
}
declare namespace LocalJSX {
    /**
     * A checkbox component
     */
    interface EsCheckbox {
        /**
          * If the field is disabled.
         */
        "disabled"?: boolean;
        /**
          * The icon to use.
         */
        "icon"?: IconDescription;
        /**
          * If the field is currently in an error state.
         */
        "invalid"?: boolean;
        /**
          * The name of the field.
         */
        "name": string;
        /**
          * Emitted when the value of the field is changed.
         */
        "onFieldchange"?: (event: EsCheckboxCustomEvent<FieldChange<boolean>>) => void;
        /**
          * If the field is editable.
         */
        "readonly"?: boolean;
        /**
          * The current value of the field.
         */
        "value": boolean;
    }
    /**
     * An optionally masked text input.
     */
    interface EsInput {
        /**
          * If the field is disabled.
         */
        "disabled"?: boolean;
        /**
          * Pass props directly to the input.
         */
        "inputProps"?: Record<string, any>;
        /**
          * If the field is currently in an error state.
         */
        "invalid"?: boolean;
        /**
          * The label of the field.
         */
        "label": string;
        /**
          * Apply an input mask
         */
        "mask"?: MaskOptions;
        /**
          * The validation messages of the field
         */
        "messages"?: ValidationMessages;
        /**
          * The name of the field.
         */
        "name": string;
        /**
          * Emitted on keyup of enter, if no modifier keys are held.
         */
        "onEnter"?: (event: EsInputCustomEvent<any>) => void;
        /**
          * Emitted when the value of the field is changed.
         */
        "onFieldchange"?: (event: EsInputCustomEvent<FieldChange<string>>) => void;
        /**
          * The placeholder for the input.
         */
        "placeholder": string;
        /**
          * If the field is editable.
         */
        "readonly"?: boolean;
        /**
          * The current value of the field.
         */
        "value": string;
    }
    /**
     * A list creator input.
     */
    interface EsInputList {
        /**
          * Icon for the add item button.
         */
        "additionIcon"?: IconDescription;
        /**
          * Text for the add item button.
         */
        "additionText"?: string;
        /**
          * Icon for the delete button.
         */
        "deleteIcon"?: IconDescription;
        /**
          * If the input is disabled.
         */
        "disabled"?: boolean;
        /**
          * The label of the field.
         */
        "label": string;
        /**
          * The validation messages of the field
         */
        "messages"?: ValidationMessages;
        /**
          * The name of the field.
         */
        "name": string;
        /**
          * Emitted when the value of the field is changed.
         */
        "onFieldchange"?: (event: EsInputListCustomEvent<FieldChange<string[]>>) => void;
        /**
          * Display a placeholder in the input.
         */
        "placeholder": string;
        /**
          * The currently selected values
         */
        "value": string[];
    }
    /**
     * A list creator input.
     */
    interface EsListCreator {
        /**
          * The icon to display next to the field
         */
        "addIcon"?: IconDescription;
        /**
          * Icon for the delete button.
         */
        "deleteIcon"?: IconDescription;
        /**
          * If the field is disabled.
         */
        "disabled"?: boolean;
        /**
          * The icon to display next to the field
         */
        "icon"?: IconDescription;
        /**
          * The label of the field.
         */
        "label": string;
        /**
          * The validation messages of the field
         */
        "messages"?: ValidationMessages;
        /**
          * The name of the field.
         */
        "name": string;
        /**
          * Emitted when the value of the field is changed.
         */
        "onFieldchange"?: (event: EsListCreatorCustomEvent<FieldChange<string[]>>) => void;
        /**
          * A list of options to choose from.
         */
        "options": TypeaheadOption[];
        /**
          * The placeholder for the input.
         */
        "placeholder": string;
        /**
          * Render the list item.
         */
        "renderItem"?: RenderFunction<[option: TypeaheadOption]>;
        /**
          * The selected item ids
         */
        "value": string[];
    }
    /**
     * An extra large input.
     */
    interface EsMegaInput {
        /**
          * If the field is disabled.
         */
        "disabled"?: boolean;
        /**
          * Pass props directly to the input.
         */
        "inputProps"?: Record<string, any>;
        /**
          * If the field is currently in an error state.
         */
        "invalid"?: boolean;
        /**
          * The label of the field.
         */
        "label": string;
        /**
          * The validation messages of the field
         */
        "messages"?: ValidationMessages;
        /**
          * The name of the field.
         */
        "name": string;
        /**
          * Emitted on keyup of enter, if no modifier keys are held.
         */
        "onEnter"?: (event: EsMegaInputCustomEvent<any>) => void;
        /**
          * Emitted when the value of the field is changed.
         */
        "onFieldchange"?: (event: EsMegaInputCustomEvent<FieldChange<string>>) => void;
        /**
          * The placeholder for the input.
         */
        "placeholder": string;
        /**
          * If the field is editable.
         */
        "readonly"?: boolean;
        /**
          * The current value of the field.
         */
        "value": string;
    }
    /**
     * A number based input. Values should be passed around as strings, as numbers can round / floating point / overflow etc if a number type is used.
     */
    interface EsNumberInput {
        /**
          * If the field is disabled.
         */
        "disabled"?: boolean;
        /**
          * Pass props directly to the input.
         */
        "inputProps"?: Record<string, any>;
        /**
          * If the field is currently in an error state.
         */
        "invalid"?: boolean;
        /**
          * The label of the field.
         */
        "label": string;
        /**
          * The validation messages of the field
         */
        "messages"?: ValidationMessages;
        /**
          * The name of the field.
         */
        "name": string;
        /**
          * Emitted on keyup of enter, if no modifier keys are held.
         */
        "onEnter"?: (event: EsNumberInputCustomEvent<any>) => void;
        /**
          * Emitted when the value of the field is changed.
         */
        "onFieldchange"?: (event: EsNumberInputCustomEvent<FieldChange<string>>) => void;
        /**
          * The placeholder for the input.
         */
        "placeholder"?: string;
        /**
          * If the field is editable.
         */
        "readonly"?: boolean;
        /**
          * Display a unit beside the input.
         */
        "unit"?: string;
        /**
          * The current value of the field.
         */
        "value": string;
    }
    /**
     * A card based single select input.
     */
    interface EsRadioCardGroup {
        /**
          * Group the cards by a key.
         */
        "groupBy"?: string;
        /**
          * Icon to display when checked.
         */
        "icon"?: IconDescription;
        /**
          * If the field is currently in an error state.
         */
        "invalid"?: boolean;
        /**
          * The id of the component that labels this input. This input doesn't bring its own label, so must be labeled externally and referenced here.
         */
        "labelledby": string;
        /**
          * The validation messages of the field
         */
        "messages"?: ValidationMessages;
        /**
          * The name of the field.
         */
        "name": string;
        /**
          * Emitted when the value of the field is changed.
         */
        "onFieldchange"?: (event: EsRadioCardGroupCustomEvent<FieldChange<string | null>>) => void;
        /**
          * The options to be displayed and chosen from.
         */
        "options": RadioCardGroupOption[];
        /**
          * Overwrite the default card renderer
         */
        "renderCard"?: RenderCard<any>;
        /**
          * The current value of the field.
         */
        "value": string | null;
    }
    /**
     * A searchable select dropdown.
     */
    interface EsSelect {
        /**
          * Icon to use as a chevron.
         */
        "chevronIcon"?: IconDescription;
        /**
          * If the field is disabled.
         */
        "disabled"?: boolean;
        /**
          * Pass props directly to the input.
         */
        "inputProps"?: Record<string, any>;
        /**
          * If the field is currently in an error state.
         */
        "invalid"?: boolean;
        /**
          * The label of the field.
         */
        "label": string;
        /**
          * The validation messages of the field
         */
        "messages"?: ValidationMessages;
        /**
          * The name of the field.
         */
        "name": string;
        /**
          * Emitted when the value of the field is changed.
         */
        "onFieldchange"?: (event: EsSelectCustomEvent<FieldChange<string | null>>) => void;
        /**
          * Pass a custom search filter function
         */
        "optionFilter"?: OptionFilter;
        /**
          * A list of options to choose from.
         */
        "options": TypeaheadOption[];
        /**
          * The placeholder for the input.
         */
        "placeholder"?: string;
        /**
          * If the field is editable.
         */
        "readonly"?: boolean;
        /**
          * Overwrite the default option renderer.
         */
        "renderOption"?: RenderTypeaheadOption<any>;
        /**
          * Overwrite the default value renderer.
         */
        "renderValue"?: RenderSelectValue<any>;
        /**
          * The current value of the field.
         */
        "value": string | null;
    }
    /**
     * A switchable switch.
     */
    interface EsSwitch {
        /**
          * Icon to display when switch is on in high contrast mode.
         */
        "activeIcon"?: IconDescription;
        /**
          * Text to display when switch is on in high contrast mode.
         */
        "activeText"?: string;
        /**
          * If the field is disabled.
         */
        "disabled"?: boolean;
        /**
          * Icon to display when switch is off in high contrast mode.
         */
        "inactiveIcon"?: IconDescription;
        /**
          * Text to display when switch is off in high contrast mode.
         */
        "inactiveText"?: string;
        /**
          * If the field is currently in an error state.
         */
        "invalid"?: boolean;
        /**
          * The name of the field.
         */
        "name": string;
        /**
          * Emitted when the value of the field is changed.
         */
        "onFieldchange"?: (event: EsSwitchCustomEvent<FieldChange<boolean>>) => void;
        /**
          * If the field is editable.
         */
        "readonly"?: boolean;
        /**
          * The current value of the field.
         */
        "value": boolean;
    }
    /**
     * A switchable switch field.
     */
    interface EsSwitchField {
        /**
          * Icon to display when switch is on in high contrast mode.
         */
        "activeIcon"?: IconDescription;
        /**
          * Text to display when switch is on in high contrast mode.
         */
        "activeText"?: string;
        /**
          * If the field is disabled.
         */
        "disabled"?: boolean;
        /**
          * Icon to display when switch is off in high contrast mode.
         */
        "inactiveIcon"?: IconDescription;
        /**
          * Text to display when switch is off in high contrast mode.
         */
        "inactiveText"?: string;
        /**
          * If the field is currently in an error state.
         */
        "invalid"?: boolean;
        /**
          * The label of the field.
         */
        "label": string;
        /**
          * The validation messages of the field
         */
        "messages"?: ValidationMessages;
        /**
          * The name of the field.
         */
        "name": string;
        /**
          * Emitted when the value of the field is changed.
         */
        "onFieldchange"?: (event: EsSwitchFieldCustomEvent<FieldChange<boolean>>) => void;
        /**
          * If the field is editable.
         */
        "readonly"?: boolean;
        /**
          * The current value of the field.
         */
        "value": boolean;
    }
    /**
     * A textarea field.
     */
    interface EsTextarea {
        /**
          * If the field is disabled.
         */
        "disabled"?: boolean;
        /**
          * Pass props directly to the input.
         */
        "inputProps"?: Record<string, any>;
        /**
          * If the field is currently in an error state.
         */
        "invalid"?: boolean;
        /**
          * The label of the field.
         */
        "label": string;
        /**
          * The validation messages of the field
         */
        "messages"?: ValidationMessages;
        /**
          * The name of the field.
         */
        "name": string;
        /**
          * Emitted when the value of the field is changed.
         */
        "onFieldchange"?: (event: EsTextareaCustomEvent<FieldChange<string>>) => void;
        /**
          * The placeholder for the input.
         */
        "placeholder": string;
        /**
          * If the field is editable.
         */
        "readonly"?: boolean;
        /**
          * The current value of the field.
         */
        "value": string;
    }
    interface EsTypeahead {
        "clearOnSelect"?: boolean;
        "closeOnSelect"?: boolean;
        "disabled"?: boolean;
        "name": string;
        "onEnter"?: (event: EsTypeaheadCustomEvent<any>) => void;
        "onFieldchange"?: (event: EsTypeaheadCustomEvent<FieldChange<string[]>>) => void;
        "optionFilter"?: OptionFilter;
        "options": TypeaheadOption[];
        "readonly"?: boolean;
        "renderField": RenderTypeaheadField;
        "renderOption"?: RenderTypeaheadOption;
        "value": string[];
        "zIndex"?: number;
    }
    /**
     * Display messages under fields.
     */
    interface EsValidationMessages {
        /**
          * Icon to diplay next to errors. (if `showIcons` or high contrast)
         */
        "errorIcon"?: IconDescription;
        /**
          * Icon to diplay next to infos. (if `showIcons` or high contrast)
         */
        "infoIcon"?: IconDescription;
        /**
          * The messages to display.
         */
        "messages"?: Partial<ValidationMessages>;
        /**
          * Display icons alongside messages.
         */
        "showIcons"?: boolean;
        /**
          * Icon to diplay next to warnings. (if `showIcons` or high contrast)
         */
        "warningIcon"?: IconDescription;
    }
    interface IntrinsicElements {
        "es-checkbox": EsCheckbox;
        "es-input": EsInput;
        "es-input-list": EsInputList;
        "es-list-creator": EsListCreator;
        "es-mega-input": EsMegaInput;
        "es-number-input": EsNumberInput;
        "es-radio-card-group": EsRadioCardGroup;
        "es-select": EsSelect;
        "es-switch": EsSwitch;
        "es-switch-field": EsSwitchField;
        "es-textarea": EsTextarea;
        "es-typeahead": EsTypeahead;
        "es-validation-messages": EsValidationMessages;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * A checkbox component
             */
            "es-checkbox": LocalJSX.EsCheckbox & JSXBase.HTMLAttributes<HTMLEsCheckboxElement>;
            /**
             * An optionally masked text input.
             */
            "es-input": LocalJSX.EsInput & JSXBase.HTMLAttributes<HTMLEsInputElement>;
            /**
             * A list creator input.
             */
            "es-input-list": LocalJSX.EsInputList & JSXBase.HTMLAttributes<HTMLEsInputListElement>;
            /**
             * A list creator input.
             */
            "es-list-creator": LocalJSX.EsListCreator & JSXBase.HTMLAttributes<HTMLEsListCreatorElement>;
            /**
             * An extra large input.
             */
            "es-mega-input": LocalJSX.EsMegaInput & JSXBase.HTMLAttributes<HTMLEsMegaInputElement>;
            /**
             * A number based input. Values should be passed around as strings, as numbers can round / floating point / overflow etc if a number type is used.
             */
            "es-number-input": LocalJSX.EsNumberInput & JSXBase.HTMLAttributes<HTMLEsNumberInputElement>;
            /**
             * A card based single select input.
             */
            "es-radio-card-group": LocalJSX.EsRadioCardGroup & JSXBase.HTMLAttributes<HTMLEsRadioCardGroupElement>;
            /**
             * A searchable select dropdown.
             */
            "es-select": LocalJSX.EsSelect & JSXBase.HTMLAttributes<HTMLEsSelectElement>;
            /**
             * A switchable switch.
             */
            "es-switch": LocalJSX.EsSwitch & JSXBase.HTMLAttributes<HTMLEsSwitchElement>;
            /**
             * A switchable switch field.
             */
            "es-switch-field": LocalJSX.EsSwitchField & JSXBase.HTMLAttributes<HTMLEsSwitchFieldElement>;
            /**
             * A textarea field.
             */
            "es-textarea": LocalJSX.EsTextarea & JSXBase.HTMLAttributes<HTMLEsTextareaElement>;
            "es-typeahead": LocalJSX.EsTypeahead & JSXBase.HTMLAttributes<HTMLEsTypeaheadElement>;
            /**
             * Display messages under fields.
             */
            "es-validation-messages": LocalJSX.EsValidationMessages & JSXBase.HTMLAttributes<HTMLEsValidationMessagesElement>;
        }
    }
}
