/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AccordianSection } from "./components/es-accordian/types";
import { VNode } from "@stencil/core";
import { BadgeColor, BadgeVariant } from "./components/es-badge/es-badge";
import { ButtonColor, ButtonVariant } from "./components/buttons/types";
import { EsCalloutVariant } from "./components/es-callout/es-callout";
import { CounterVariant } from "./components/es-counter/es-counter";
import { AttachmentX, AttachmentY, Constrain, Position, PositionX, PositionY } from "./utils/calcPosition";
import { Checkpoint } from "./components/es-progression/es-progression";
import { Status } from "./components/es-status/es-status";
import { TableCells } from "./components/es-table/types";
import { Tab } from "./components/es-tabs/types";
import { Bread, Toast } from "./components/toast/types";
import { WizardPage } from "./components/es-wizard/types";
export namespace Components {
    interface EsAccordian {
        "sections": AccordianSection[];
        "steps": boolean;
    }
    interface EsBackdrop {
        "close": () => Promise<unknown>;
        "renderNode": (node: VNode | null) => Promise<void>;
        "showBackdrop": boolean;
    }
    interface EsBadge {
        /**
          * Choose the color variant of the badge
         */
        "color": BadgeColor;
        /**
          * What number to display in the counter (or if the dot should display)
         */
        "count": number;
        /**
          * Show the dot and counter even if the count 0 (or negative)
         */
        "showZero": boolean;
        /**
          * The base size (in px) of the counter (has no effect on the dot)
         */
        "size"?: number;
        /**
          * Select the display variant of the badge
         */
        "variant": BadgeVariant;
    }
    interface EsButton {
        "color": ButtonColor;
        "disabled"?: boolean;
        "form"?: string;
        "type": string;
        "variant": ButtonVariant;
    }
    interface EsButtonLink {
        "anchorClass": string;
        "anchorId"?: string;
        "anchorRole"?: string;
        "anchorTabIndex"?: string;
        "anchorTitle"?: string;
        "ariaHaspopup"?: string;
        "ariaLabel"?: string;
        "ariaPosinset"?: string;
        "ariaSetsize"?: number;
        "color": ButtonColor;
        "disabled"?: boolean;
        "forceRefresh"?: boolean;
        "target"?: string;
        "url"?: string;
        "variant": ButtonVariant;
    }
    interface EsCallout {
        "heading": string;
        "icon"?: string;
        "variant": EsCalloutVariant;
    }
    interface EsCopy {
        "copy": () => Promise<void>;
    }
    interface EsCounter {
        "count": number;
        "size": number;
        "variant": CounterVariant;
    }
    interface EsIcon {
        "angle": number;
        "icon": string;
        "size": number;
        "spin"?: boolean;
        "spinDirection": 'clockwise' | 'antiClockwise';
        "spinEnd": () => Promise<void>;
    }
    interface EsModal {
        "footer": boolean;
        "header": boolean;
    }
    interface EsPopover {
        "attachTo"?: HTMLElement;
        "attachmentX": AttachmentX;
        "attachmentY": AttachmentY;
        "backdrop": boolean;
        "constrain": Constrain;
        "offsetX": number;
        "offsetY": number;
        "open": boolean;
        "popperClass"?: string;
        "positionX": PositionX;
        "positionY": PositionY;
        "target": string;
        "trapFocus": boolean;
    }
    interface EsPopper {
        "backdrop": boolean;
        "trapFocus": boolean;
    }
    interface EsPopperInner {
        "setPosition": (position: Position) => Promise<void>;
    }
    interface EsPortal {
        "attachElement": () => Promise<void>;
        "backdrop": boolean;
        "detatchElement": () => Promise<void>;
        "element": VNode;
        "open": boolean;
        "target": string;
    }
    interface EsProgression {
        "checkpoints": Checkpoint[];
        "location": string;
    }
    interface EsResizeObserver {
    }
    interface EsStatus {
        "status": Status;
    }
    interface EsTable {
        "cells": TableCells<any>;
        "columns"?: string[];
        "getCellData": <T = string>(key: T) => any;
        "headless": boolean;
        "identifier": string;
        "linkRowTo"?: (row: any) => string;
        "renderExpansion": (key: string) => VNode | null;
        "rowClass": (
        row: any,
    ) => Record<string, boolean> | string | undefined;
        "rowTakesFocus"?: boolean;
        "rows": any[];
    }
    interface EsTableDetail {
        "cells": TableCells<any>;
        "columns"?: Array<string>;
        "data": any;
        "identifier": string;
    }
    interface EsTableDetailHeader {
        "actionsCell": string;
        "cells": TableCells<any>;
        "data": any;
        "identifier": string;
        "titleKey": string;
    }
    interface EsTableNested {
        "activePath"?: string[];
        "canExpand": (key: string, data: any) => boolean;
        "cells": TableCells<any>;
        "columns"?: string[];
        "getCellData"?: <T = string>(key: T) => any;
        "getNestedCellData"?: <T = string>(key: T) => any;
        "getNestedRows"?: (key: string) => any[] | undefined;
        "linkRowTo"?: (row: any) => string;
        "loadNested"?: (key: string, data: any) => Promise<void>;
        "nestedColumns"?: string[];
        "nestedIdentifier": string;
        "nestedRowTakesFocus"?: boolean;
        "outerIdentifier": string;
        "rowClass": (
        row: any,
    ) => Record<string, boolean> | string | undefined;
        "rowTakesFocus"?: boolean;
        "rows": any[];
    }
    interface EsTabs {
        "activeParam": string;
        "tabs": Tab[];
    }
    interface EsToast {
        "close": () => Promise<unknown>;
        "count": Toast['count'];
        "icon": Toast['icon'];
        "level": Toast['level'];
    }
    interface EsToaster {
        "popToast": ({ message, title, level, duration, icon, onClick, }: Bread) => Promise<void>;
    }
    interface EsWizard {
        "location": string;
        "pages": WizardPage[];
        "scrollOffset": number;
    }
}
declare global {
    interface HTMLEsAccordianElement extends Components.EsAccordian, HTMLStencilElement {
    }
    var HTMLEsAccordianElement: {
        prototype: HTMLEsAccordianElement;
        new (): HTMLEsAccordianElement;
    };
    interface HTMLEsBackdropElement extends Components.EsBackdrop, HTMLStencilElement {
    }
    var HTMLEsBackdropElement: {
        prototype: HTMLEsBackdropElement;
        new (): HTMLEsBackdropElement;
    };
    interface HTMLEsBadgeElement extends Components.EsBadge, HTMLStencilElement {
    }
    var HTMLEsBadgeElement: {
        prototype: HTMLEsBadgeElement;
        new (): HTMLEsBadgeElement;
    };
    interface HTMLEsButtonElement extends Components.EsButton, HTMLStencilElement {
    }
    var HTMLEsButtonElement: {
        prototype: HTMLEsButtonElement;
        new (): HTMLEsButtonElement;
    };
    interface HTMLEsButtonLinkElement extends Components.EsButtonLink, HTMLStencilElement {
    }
    var HTMLEsButtonLinkElement: {
        prototype: HTMLEsButtonLinkElement;
        new (): HTMLEsButtonLinkElement;
    };
    interface HTMLEsCalloutElement extends Components.EsCallout, HTMLStencilElement {
    }
    var HTMLEsCalloutElement: {
        prototype: HTMLEsCalloutElement;
        new (): HTMLEsCalloutElement;
    };
    interface HTMLEsCopyElement extends Components.EsCopy, HTMLStencilElement {
    }
    var HTMLEsCopyElement: {
        prototype: HTMLEsCopyElement;
        new (): HTMLEsCopyElement;
    };
    interface HTMLEsCounterElement extends Components.EsCounter, HTMLStencilElement {
    }
    var HTMLEsCounterElement: {
        prototype: HTMLEsCounterElement;
        new (): HTMLEsCounterElement;
    };
    interface HTMLEsIconElement extends Components.EsIcon, HTMLStencilElement {
    }
    var HTMLEsIconElement: {
        prototype: HTMLEsIconElement;
        new (): HTMLEsIconElement;
    };
    interface HTMLEsModalElement extends Components.EsModal, HTMLStencilElement {
    }
    var HTMLEsModalElement: {
        prototype: HTMLEsModalElement;
        new (): HTMLEsModalElement;
    };
    interface HTMLEsPopoverElement extends Components.EsPopover, HTMLStencilElement {
    }
    var HTMLEsPopoverElement: {
        prototype: HTMLEsPopoverElement;
        new (): HTMLEsPopoverElement;
    };
    interface HTMLEsPopperElement extends Components.EsPopper, HTMLStencilElement {
    }
    var HTMLEsPopperElement: {
        prototype: HTMLEsPopperElement;
        new (): HTMLEsPopperElement;
    };
    interface HTMLEsPopperInnerElement extends Components.EsPopperInner, HTMLStencilElement {
    }
    var HTMLEsPopperInnerElement: {
        prototype: HTMLEsPopperInnerElement;
        new (): HTMLEsPopperInnerElement;
    };
    interface HTMLEsPortalElement extends Components.EsPortal, HTMLStencilElement {
    }
    var HTMLEsPortalElement: {
        prototype: HTMLEsPortalElement;
        new (): HTMLEsPortalElement;
    };
    interface HTMLEsProgressionElement extends Components.EsProgression, HTMLStencilElement {
    }
    var HTMLEsProgressionElement: {
        prototype: HTMLEsProgressionElement;
        new (): HTMLEsProgressionElement;
    };
    interface HTMLEsResizeObserverElement extends Components.EsResizeObserver, HTMLStencilElement {
    }
    var HTMLEsResizeObserverElement: {
        prototype: HTMLEsResizeObserverElement;
        new (): HTMLEsResizeObserverElement;
    };
    interface HTMLEsStatusElement extends Components.EsStatus, HTMLStencilElement {
    }
    var HTMLEsStatusElement: {
        prototype: HTMLEsStatusElement;
        new (): HTMLEsStatusElement;
    };
    interface HTMLEsTableElement extends Components.EsTable, HTMLStencilElement {
    }
    var HTMLEsTableElement: {
        prototype: HTMLEsTableElement;
        new (): HTMLEsTableElement;
    };
    interface HTMLEsTableDetailElement extends Components.EsTableDetail, HTMLStencilElement {
    }
    var HTMLEsTableDetailElement: {
        prototype: HTMLEsTableDetailElement;
        new (): HTMLEsTableDetailElement;
    };
    interface HTMLEsTableDetailHeaderElement extends Components.EsTableDetailHeader, HTMLStencilElement {
    }
    var HTMLEsTableDetailHeaderElement: {
        prototype: HTMLEsTableDetailHeaderElement;
        new (): HTMLEsTableDetailHeaderElement;
    };
    interface HTMLEsTableNestedElement extends Components.EsTableNested, HTMLStencilElement {
    }
    var HTMLEsTableNestedElement: {
        prototype: HTMLEsTableNestedElement;
        new (): HTMLEsTableNestedElement;
    };
    interface HTMLEsTabsElement extends Components.EsTabs, HTMLStencilElement {
    }
    var HTMLEsTabsElement: {
        prototype: HTMLEsTabsElement;
        new (): HTMLEsTabsElement;
    };
    interface HTMLEsToastElement extends Components.EsToast, HTMLStencilElement {
    }
    var HTMLEsToastElement: {
        prototype: HTMLEsToastElement;
        new (): HTMLEsToastElement;
    };
    interface HTMLEsToasterElement extends Components.EsToaster, HTMLStencilElement {
    }
    var HTMLEsToasterElement: {
        prototype: HTMLEsToasterElement;
        new (): HTMLEsToasterElement;
    };
    interface HTMLEsWizardElement extends Components.EsWizard, HTMLStencilElement {
    }
    var HTMLEsWizardElement: {
        prototype: HTMLEsWizardElement;
        new (): HTMLEsWizardElement;
    };
    interface HTMLElementTagNameMap {
        "es-accordian": HTMLEsAccordianElement;
        "es-backdrop": HTMLEsBackdropElement;
        "es-badge": HTMLEsBadgeElement;
        "es-button": HTMLEsButtonElement;
        "es-button-link": HTMLEsButtonLinkElement;
        "es-callout": HTMLEsCalloutElement;
        "es-copy": HTMLEsCopyElement;
        "es-counter": HTMLEsCounterElement;
        "es-icon": HTMLEsIconElement;
        "es-modal": HTMLEsModalElement;
        "es-popover": HTMLEsPopoverElement;
        "es-popper": HTMLEsPopperElement;
        "es-popper-inner": HTMLEsPopperInnerElement;
        "es-portal": HTMLEsPortalElement;
        "es-progression": HTMLEsProgressionElement;
        "es-resize-observer": HTMLEsResizeObserverElement;
        "es-status": HTMLEsStatusElement;
        "es-table": HTMLEsTableElement;
        "es-table-detail": HTMLEsTableDetailElement;
        "es-table-detail-header": HTMLEsTableDetailHeaderElement;
        "es-table-nested": HTMLEsTableNestedElement;
        "es-tabs": HTMLEsTabsElement;
        "es-toast": HTMLEsToastElement;
        "es-toaster": HTMLEsToasterElement;
        "es-wizard": HTMLEsWizardElement;
    }
}
declare namespace LocalJSX {
    interface EsAccordian {
        "sections": AccordianSection[];
        "steps"?: boolean;
    }
    interface EsBackdrop {
        "onClosed"?: (event: CustomEvent<any>) => void;
        "onRequestClose"?: (event: CustomEvent<any>) => void;
        "showBackdrop"?: boolean;
    }
    interface EsBadge {
        /**
          * Choose the color variant of the badge
         */
        "color"?: BadgeColor;
        /**
          * What number to display in the counter (or if the dot should display)
         */
        "count": number;
        /**
          * Show the dot and counter even if the count 0 (or negative)
         */
        "showZero"?: boolean;
        /**
          * The base size (in px) of the counter (has no effect on the dot)
         */
        "size"?: number;
        /**
          * Select the display variant of the badge
         */
        "variant"?: BadgeVariant;
    }
    interface EsButton {
        "color"?: ButtonColor;
        "disabled"?: boolean;
        "form"?: string;
        "type"?: string;
        "variant"?: ButtonVariant;
    }
    interface EsButtonLink {
        "anchorClass"?: string;
        "anchorId"?: string;
        "anchorRole"?: string;
        "anchorTabIndex"?: string;
        "anchorTitle"?: string;
        "ariaHaspopup"?: string;
        "ariaLabel"?: string;
        "ariaPosinset"?: string;
        "ariaSetsize"?: number;
        "color"?: ButtonColor;
        "disabled"?: boolean;
        "forceRefresh"?: boolean;
        "target"?: string;
        "url"?: string;
        "variant"?: ButtonVariant;
    }
    interface EsCallout {
        "heading": string;
        "icon"?: string;
        "variant"?: EsCalloutVariant;
    }
    interface EsCopy {
    }
    interface EsCounter {
        "count"?: number;
        "size"?: number;
        "variant"?: CounterVariant;
    }
    interface EsIcon {
        "angle"?: number;
        "icon": string;
        "size"?: number;
        "spin"?: boolean;
        "spinDirection"?: 'clockwise' | 'antiClockwise';
    }
    interface EsModal {
        "footer"?: boolean;
        "header"?: boolean;
        "onRequestClose"?: (event: CustomEvent<any>) => void;
    }
    interface EsPopover {
        "attachTo"?: HTMLElement;
        "attachmentX"?: AttachmentX;
        "attachmentY"?: AttachmentY;
        "backdrop"?: boolean;
        "constrain"?: Constrain;
        "offsetX"?: number;
        "offsetY"?: number;
        "onRequestClose"?: (event: CustomEvent<any>) => void;
        "open"?: boolean;
        "popperClass"?: string;
        "positionX"?: PositionX;
        "positionY"?: PositionY;
        "target"?: string;
        "trapFocus"?: boolean;
    }
    interface EsPopper {
        "backdrop"?: boolean;
        "onRequestClose"?: (event: CustomEvent<any>) => void;
        "trapFocus"?: boolean;
    }
    interface EsPopperInner {
    }
    interface EsPortal {
        "backdrop"?: boolean;
        "element": VNode;
        "onRequestClose"?: (event: CustomEvent<any>) => void;
        "open"?: boolean;
        "target"?: string;
    }
    interface EsProgression {
        "checkpoints": Checkpoint[];
        "location": string;
        "onProgressionRequest"?: (event: CustomEvent<any>) => void;
    }
    interface EsResizeObserver {
        "onSizeChanged"?: (event: CustomEvent<DOMRectReadOnly>) => void;
    }
    interface EsStatus {
        "status": Status;
    }
    interface EsTable {
        "cells": TableCells<any>;
        "columns"?: string[];
        "getCellData"?: <T = string>(key: T) => any;
        "headless"?: boolean;
        "identifier"?: string;
        "linkRowTo"?: (row: any) => string;
        "onClickRow"?: (event: CustomEvent<any>) => void;
        "renderExpansion"?: (key: string) => VNode | null;
        "rowClass"?: (
        row: any,
    ) => Record<string, boolean> | string | undefined;
        "rowTakesFocus"?: boolean;
        "rows": any[];
    }
    interface EsTableDetail {
        "cells": TableCells<any>;
        "columns"?: Array<string>;
        "data": any;
        "identifier"?: string;
    }
    interface EsTableDetailHeader {
        "actionsCell"?: string;
        "cells": TableCells<any>;
        "data": any;
        "identifier"?: string;
        "titleKey": string;
    }
    interface EsTableNested {
        "activePath"?: string[];
        "canExpand"?: (key: string, data: any) => boolean;
        "cells": TableCells<any>;
        "columns"?: string[];
        "getCellData"?: <T = string>(key: T) => any;
        "getNestedCellData"?: <T = string>(key: T) => any;
        "getNestedRows"?: (key: string) => any[] | undefined;
        "linkRowTo"?: (row: any) => string;
        "loadNested"?: (key: string, data: any) => Promise<void>;
        "nestedColumns"?: string[];
        "nestedIdentifier"?: string;
        "nestedRowTakesFocus"?: boolean;
        "onClickRow"?: (event: CustomEvent<any>) => void;
        "onExpansion"?: (event: CustomEvent<{ data: any; key: string }>) => void;
        "outerIdentifier"?: string;
        "rowClass"?: (
        row: any,
    ) => Record<string, boolean> | string | undefined;
        "rowTakesFocus"?: boolean;
        "rows": any[];
    }
    interface EsTabs {
        "activeParam"?: string;
        "tabs": Tab[];
    }
    interface EsToast {
        "count": Toast['count'];
        "icon": Toast['icon'];
        "level": Toast['level'];
    }
    interface EsToaster {
    }
    interface EsWizard {
        "location": string;
        "pages": WizardPage[];
        "scrollOffset"?: number;
    }
    interface IntrinsicElements {
        "es-accordian": EsAccordian;
        "es-backdrop": EsBackdrop;
        "es-badge": EsBadge;
        "es-button": EsButton;
        "es-button-link": EsButtonLink;
        "es-callout": EsCallout;
        "es-copy": EsCopy;
        "es-counter": EsCounter;
        "es-icon": EsIcon;
        "es-modal": EsModal;
        "es-popover": EsPopover;
        "es-popper": EsPopper;
        "es-popper-inner": EsPopperInner;
        "es-portal": EsPortal;
        "es-progression": EsProgression;
        "es-resize-observer": EsResizeObserver;
        "es-status": EsStatus;
        "es-table": EsTable;
        "es-table-detail": EsTableDetail;
        "es-table-detail-header": EsTableDetailHeader;
        "es-table-nested": EsTableNested;
        "es-tabs": EsTabs;
        "es-toast": EsToast;
        "es-toaster": EsToaster;
        "es-wizard": EsWizard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "es-accordian": LocalJSX.EsAccordian & JSXBase.HTMLAttributes<HTMLEsAccordianElement>;
            "es-backdrop": LocalJSX.EsBackdrop & JSXBase.HTMLAttributes<HTMLEsBackdropElement>;
            "es-badge": LocalJSX.EsBadge & JSXBase.HTMLAttributes<HTMLEsBadgeElement>;
            "es-button": LocalJSX.EsButton & JSXBase.HTMLAttributes<HTMLEsButtonElement>;
            "es-button-link": LocalJSX.EsButtonLink & JSXBase.HTMLAttributes<HTMLEsButtonLinkElement>;
            "es-callout": LocalJSX.EsCallout & JSXBase.HTMLAttributes<HTMLEsCalloutElement>;
            "es-copy": LocalJSX.EsCopy & JSXBase.HTMLAttributes<HTMLEsCopyElement>;
            "es-counter": LocalJSX.EsCounter & JSXBase.HTMLAttributes<HTMLEsCounterElement>;
            "es-icon": LocalJSX.EsIcon & JSXBase.HTMLAttributes<HTMLEsIconElement>;
            "es-modal": LocalJSX.EsModal & JSXBase.HTMLAttributes<HTMLEsModalElement>;
            "es-popover": LocalJSX.EsPopover & JSXBase.HTMLAttributes<HTMLEsPopoverElement>;
            "es-popper": LocalJSX.EsPopper & JSXBase.HTMLAttributes<HTMLEsPopperElement>;
            "es-popper-inner": LocalJSX.EsPopperInner & JSXBase.HTMLAttributes<HTMLEsPopperInnerElement>;
            "es-portal": LocalJSX.EsPortal & JSXBase.HTMLAttributes<HTMLEsPortalElement>;
            "es-progression": LocalJSX.EsProgression & JSXBase.HTMLAttributes<HTMLEsProgressionElement>;
            "es-resize-observer": LocalJSX.EsResizeObserver & JSXBase.HTMLAttributes<HTMLEsResizeObserverElement>;
            "es-status": LocalJSX.EsStatus & JSXBase.HTMLAttributes<HTMLEsStatusElement>;
            "es-table": LocalJSX.EsTable & JSXBase.HTMLAttributes<HTMLEsTableElement>;
            "es-table-detail": LocalJSX.EsTableDetail & JSXBase.HTMLAttributes<HTMLEsTableDetailElement>;
            "es-table-detail-header": LocalJSX.EsTableDetailHeader & JSXBase.HTMLAttributes<HTMLEsTableDetailHeaderElement>;
            "es-table-nested": LocalJSX.EsTableNested & JSXBase.HTMLAttributes<HTMLEsTableNestedElement>;
            "es-tabs": LocalJSX.EsTabs & JSXBase.HTMLAttributes<HTMLEsTabsElement>;
            "es-toast": LocalJSX.EsToast & JSXBase.HTMLAttributes<HTMLEsToastElement>;
            "es-toaster": LocalJSX.EsToaster & JSXBase.HTMLAttributes<HTMLEsToasterElement>;
            "es-wizard": LocalJSX.EsWizard & JSXBase.HTMLAttributes<HTMLEsWizardElement>;
        }
    }
}
