/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EsdRoot {
    }
}
declare global {
    interface HTMLEsdRootElement extends Components.EsdRoot, HTMLStencilElement {
    }
    var HTMLEsdRootElement: {
        prototype: HTMLEsdRootElement;
        new (): HTMLEsdRootElement;
    };
    interface HTMLElementTagNameMap {
        "esd-root": HTMLEsdRootElement;
    }
}
declare namespace LocalJSX {
    interface EsdRoot {
    }
    interface IntrinsicElements {
        "esd-root": EsdRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "esd-root": LocalJSX.EsdRoot & JSXBase.HTMLAttributes<HTMLEsdRootElement>;
        }
    }
}
