/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { backgroundVariant } from "./components/layout/docs-background/docs-background";
import { Crumb } from "./components/layout/docs-breadcrumb/docs-breadcrumb";
import { JsonDocs, JsonDocsProp, JsonDocsStyle } from "@stencil/core/internal";
import { Lib } from "sitemap";
import { PageState } from "./components/layout/docs-page/docs-page";
import { VNode } from "@stencil/core";
import { SidebarLinkVariant } from "./components/layout/docs-sidebar/components/docs-sidebar-link/docs-sidebar-link";
import { JSONOutput } from "typedoc";
export namespace Components {
    interface DocsBackground {
        /**
          * Sets the background variant.
         */
        "variant": backgroundVariant;
    }
    interface DocsBreadcrumb {
        "crumbs": Crumb[];
        "noValidate": boolean;
    }
    interface DocsCode {
        "code": string;
        "language": string;
    }
    interface DocsComponentDocs {
        "comp": JsonDocs['components'][0];
        "lib": Lib;
    }
    interface DocsHeader {
        "background": HTMLDocsBackgroundElement['variant'] | 'none';
    }
    interface DocsHome {
    }
    interface DocsLogo {
        "height": number;
        "width": number;
    }
    interface DocsPackage {
        "lib": Lib;
    }
    interface DocsPage {
        "crumbs"?: HTMLDocsBreadcrumbElement['crumbs'];
        "empty": boolean;
        "headerRight"?: () => VNode | VNode[];
        "headerTitle"?: string | false;
        "noSidebar"?: boolean;
        "pageTitle": string;
        "renderEmptyState"?: () => VNode | VNode[];
        "state": PageState;
    }
    interface DocsPageTitle {
    }
    interface DocsPropsTable {
        "props": JsonDocsProp[];
    }
    interface DocsRoot {
    }
    interface DocsSidebar {
    }
    interface DocsSidebarDropdown {
        "active": Lib;
    }
    interface DocsSidebarLink {
        "disabled": boolean;
        "icon"?: string;
        "url"?: string;
        "urlMatch"?: string;
        "variant": SidebarLinkVariant;
    }
    interface DocsSidebarSection {
        "sectionTitle": string;
    }
    interface DocsSidebarTree {
        "icon"?: string;
        "name": string;
        "root": boolean;
        "url"?: string;
        "urlMatch"?: string;
    }
    interface DocsStylesTable {
        "styles": JsonDocsStyle[];
    }
    interface DocsTypeTable {
        "declaration": JSONOutput.DeclarationReflection;
    }
    interface DocsUsage {
        "usage": string;
    }
    interface EsFooter {
        "noSidebar"?: boolean;
    }
}
declare global {
    interface HTMLDocsBackgroundElement extends Components.DocsBackground, HTMLStencilElement {
    }
    var HTMLDocsBackgroundElement: {
        prototype: HTMLDocsBackgroundElement;
        new (): HTMLDocsBackgroundElement;
    };
    interface HTMLDocsBreadcrumbElement extends Components.DocsBreadcrumb, HTMLStencilElement {
    }
    var HTMLDocsBreadcrumbElement: {
        prototype: HTMLDocsBreadcrumbElement;
        new (): HTMLDocsBreadcrumbElement;
    };
    interface HTMLDocsCodeElement extends Components.DocsCode, HTMLStencilElement {
    }
    var HTMLDocsCodeElement: {
        prototype: HTMLDocsCodeElement;
        new (): HTMLDocsCodeElement;
    };
    interface HTMLDocsComponentDocsElement extends Components.DocsComponentDocs, HTMLStencilElement {
    }
    var HTMLDocsComponentDocsElement: {
        prototype: HTMLDocsComponentDocsElement;
        new (): HTMLDocsComponentDocsElement;
    };
    interface HTMLDocsHeaderElement extends Components.DocsHeader, HTMLStencilElement {
    }
    var HTMLDocsHeaderElement: {
        prototype: HTMLDocsHeaderElement;
        new (): HTMLDocsHeaderElement;
    };
    interface HTMLDocsHomeElement extends Components.DocsHome, HTMLStencilElement {
    }
    var HTMLDocsHomeElement: {
        prototype: HTMLDocsHomeElement;
        new (): HTMLDocsHomeElement;
    };
    interface HTMLDocsLogoElement extends Components.DocsLogo, HTMLStencilElement {
    }
    var HTMLDocsLogoElement: {
        prototype: HTMLDocsLogoElement;
        new (): HTMLDocsLogoElement;
    };
    interface HTMLDocsPackageElement extends Components.DocsPackage, HTMLStencilElement {
    }
    var HTMLDocsPackageElement: {
        prototype: HTMLDocsPackageElement;
        new (): HTMLDocsPackageElement;
    };
    interface HTMLDocsPageElement extends Components.DocsPage, HTMLStencilElement {
    }
    var HTMLDocsPageElement: {
        prototype: HTMLDocsPageElement;
        new (): HTMLDocsPageElement;
    };
    interface HTMLDocsPageTitleElement extends Components.DocsPageTitle, HTMLStencilElement {
    }
    var HTMLDocsPageTitleElement: {
        prototype: HTMLDocsPageTitleElement;
        new (): HTMLDocsPageTitleElement;
    };
    interface HTMLDocsPropsTableElement extends Components.DocsPropsTable, HTMLStencilElement {
    }
    var HTMLDocsPropsTableElement: {
        prototype: HTMLDocsPropsTableElement;
        new (): HTMLDocsPropsTableElement;
    };
    interface HTMLDocsRootElement extends Components.DocsRoot, HTMLStencilElement {
    }
    var HTMLDocsRootElement: {
        prototype: HTMLDocsRootElement;
        new (): HTMLDocsRootElement;
    };
    interface HTMLDocsSidebarElement extends Components.DocsSidebar, HTMLStencilElement {
    }
    var HTMLDocsSidebarElement: {
        prototype: HTMLDocsSidebarElement;
        new (): HTMLDocsSidebarElement;
    };
    interface HTMLDocsSidebarDropdownElement extends Components.DocsSidebarDropdown, HTMLStencilElement {
    }
    var HTMLDocsSidebarDropdownElement: {
        prototype: HTMLDocsSidebarDropdownElement;
        new (): HTMLDocsSidebarDropdownElement;
    };
    interface HTMLDocsSidebarLinkElement extends Components.DocsSidebarLink, HTMLStencilElement {
    }
    var HTMLDocsSidebarLinkElement: {
        prototype: HTMLDocsSidebarLinkElement;
        new (): HTMLDocsSidebarLinkElement;
    };
    interface HTMLDocsSidebarSectionElement extends Components.DocsSidebarSection, HTMLStencilElement {
    }
    var HTMLDocsSidebarSectionElement: {
        prototype: HTMLDocsSidebarSectionElement;
        new (): HTMLDocsSidebarSectionElement;
    };
    interface HTMLDocsSidebarTreeElement extends Components.DocsSidebarTree, HTMLStencilElement {
    }
    var HTMLDocsSidebarTreeElement: {
        prototype: HTMLDocsSidebarTreeElement;
        new (): HTMLDocsSidebarTreeElement;
    };
    interface HTMLDocsStylesTableElement extends Components.DocsStylesTable, HTMLStencilElement {
    }
    var HTMLDocsStylesTableElement: {
        prototype: HTMLDocsStylesTableElement;
        new (): HTMLDocsStylesTableElement;
    };
    interface HTMLDocsTypeTableElement extends Components.DocsTypeTable, HTMLStencilElement {
    }
    var HTMLDocsTypeTableElement: {
        prototype: HTMLDocsTypeTableElement;
        new (): HTMLDocsTypeTableElement;
    };
    interface HTMLDocsUsageElement extends Components.DocsUsage, HTMLStencilElement {
    }
    var HTMLDocsUsageElement: {
        prototype: HTMLDocsUsageElement;
        new (): HTMLDocsUsageElement;
    };
    interface HTMLEsFooterElement extends Components.EsFooter, HTMLStencilElement {
    }
    var HTMLEsFooterElement: {
        prototype: HTMLEsFooterElement;
        new (): HTMLEsFooterElement;
    };
    interface HTMLElementTagNameMap {
        "docs-background": HTMLDocsBackgroundElement;
        "docs-breadcrumb": HTMLDocsBreadcrumbElement;
        "docs-code": HTMLDocsCodeElement;
        "docs-component-docs": HTMLDocsComponentDocsElement;
        "docs-header": HTMLDocsHeaderElement;
        "docs-home": HTMLDocsHomeElement;
        "docs-logo": HTMLDocsLogoElement;
        "docs-package": HTMLDocsPackageElement;
        "docs-page": HTMLDocsPageElement;
        "docs-page-title": HTMLDocsPageTitleElement;
        "docs-props-table": HTMLDocsPropsTableElement;
        "docs-root": HTMLDocsRootElement;
        "docs-sidebar": HTMLDocsSidebarElement;
        "docs-sidebar-dropdown": HTMLDocsSidebarDropdownElement;
        "docs-sidebar-link": HTMLDocsSidebarLinkElement;
        "docs-sidebar-section": HTMLDocsSidebarSectionElement;
        "docs-sidebar-tree": HTMLDocsSidebarTreeElement;
        "docs-styles-table": HTMLDocsStylesTableElement;
        "docs-type-table": HTMLDocsTypeTableElement;
        "docs-usage": HTMLDocsUsageElement;
        "es-footer": HTMLEsFooterElement;
    }
}
declare namespace LocalJSX {
    interface DocsBackground {
        /**
          * Sets the background variant.
         */
        "variant"?: backgroundVariant;
    }
    interface DocsBreadcrumb {
        "crumbs"?: Crumb[];
        "noValidate"?: boolean;
    }
    interface DocsCode {
        "code": string;
        "language": string;
    }
    interface DocsComponentDocs {
        "comp": JsonDocs['components'][0];
        "lib": Lib;
    }
    interface DocsHeader {
        "background"?: HTMLDocsBackgroundElement['variant'] | 'none';
    }
    interface DocsHome {
    }
    interface DocsLogo {
        "height"?: number;
        "width"?: number;
    }
    interface DocsPackage {
        "lib": Lib;
    }
    interface DocsPage {
        "crumbs"?: HTMLDocsBreadcrumbElement['crumbs'];
        "empty"?: boolean;
        "headerRight"?: () => VNode | VNode[];
        "headerTitle"?: string | false;
        "noSidebar"?: boolean;
        "pageTitle": string;
        "renderEmptyState"?: () => VNode | VNode[];
        "state"?: PageState;
    }
    interface DocsPageTitle {
    }
    interface DocsPropsTable {
        "props": JsonDocsProp[];
    }
    interface DocsRoot {
    }
    interface DocsSidebar {
    }
    interface DocsSidebarDropdown {
        "active": Lib;
    }
    interface DocsSidebarLink {
        "disabled"?: boolean;
        "icon"?: string;
        "url"?: string;
        "urlMatch"?: string;
        "variant"?: SidebarLinkVariant;
    }
    interface DocsSidebarSection {
        "sectionTitle": string;
    }
    interface DocsSidebarTree {
        "icon"?: string;
        "name": string;
        "root"?: boolean;
        "url"?: string;
        "urlMatch"?: string;
    }
    interface DocsStylesTable {
        "styles": JsonDocsStyle[];
    }
    interface DocsTypeTable {
        "declaration": JSONOutput.DeclarationReflection;
    }
    interface DocsUsage {
        "usage": string;
    }
    interface EsFooter {
        "noSidebar"?: boolean;
    }
    interface IntrinsicElements {
        "docs-background": DocsBackground;
        "docs-breadcrumb": DocsBreadcrumb;
        "docs-code": DocsCode;
        "docs-component-docs": DocsComponentDocs;
        "docs-header": DocsHeader;
        "docs-home": DocsHome;
        "docs-logo": DocsLogo;
        "docs-package": DocsPackage;
        "docs-page": DocsPage;
        "docs-page-title": DocsPageTitle;
        "docs-props-table": DocsPropsTable;
        "docs-root": DocsRoot;
        "docs-sidebar": DocsSidebar;
        "docs-sidebar-dropdown": DocsSidebarDropdown;
        "docs-sidebar-link": DocsSidebarLink;
        "docs-sidebar-section": DocsSidebarSection;
        "docs-sidebar-tree": DocsSidebarTree;
        "docs-styles-table": DocsStylesTable;
        "docs-type-table": DocsTypeTable;
        "docs-usage": DocsUsage;
        "es-footer": EsFooter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "docs-background": LocalJSX.DocsBackground & JSXBase.HTMLAttributes<HTMLDocsBackgroundElement>;
            "docs-breadcrumb": LocalJSX.DocsBreadcrumb & JSXBase.HTMLAttributes<HTMLDocsBreadcrumbElement>;
            "docs-code": LocalJSX.DocsCode & JSXBase.HTMLAttributes<HTMLDocsCodeElement>;
            "docs-component-docs": LocalJSX.DocsComponentDocs & JSXBase.HTMLAttributes<HTMLDocsComponentDocsElement>;
            "docs-header": LocalJSX.DocsHeader & JSXBase.HTMLAttributes<HTMLDocsHeaderElement>;
            "docs-home": LocalJSX.DocsHome & JSXBase.HTMLAttributes<HTMLDocsHomeElement>;
            "docs-logo": LocalJSX.DocsLogo & JSXBase.HTMLAttributes<HTMLDocsLogoElement>;
            "docs-package": LocalJSX.DocsPackage & JSXBase.HTMLAttributes<HTMLDocsPackageElement>;
            "docs-page": LocalJSX.DocsPage & JSXBase.HTMLAttributes<HTMLDocsPageElement>;
            "docs-page-title": LocalJSX.DocsPageTitle & JSXBase.HTMLAttributes<HTMLDocsPageTitleElement>;
            "docs-props-table": LocalJSX.DocsPropsTable & JSXBase.HTMLAttributes<HTMLDocsPropsTableElement>;
            "docs-root": LocalJSX.DocsRoot & JSXBase.HTMLAttributes<HTMLDocsRootElement>;
            "docs-sidebar": LocalJSX.DocsSidebar & JSXBase.HTMLAttributes<HTMLDocsSidebarElement>;
            "docs-sidebar-dropdown": LocalJSX.DocsSidebarDropdown & JSXBase.HTMLAttributes<HTMLDocsSidebarDropdownElement>;
            "docs-sidebar-link": LocalJSX.DocsSidebarLink & JSXBase.HTMLAttributes<HTMLDocsSidebarLinkElement>;
            "docs-sidebar-section": LocalJSX.DocsSidebarSection & JSXBase.HTMLAttributes<HTMLDocsSidebarSectionElement>;
            "docs-sidebar-tree": LocalJSX.DocsSidebarTree & JSXBase.HTMLAttributes<HTMLDocsSidebarTreeElement>;
            "docs-styles-table": LocalJSX.DocsStylesTable & JSXBase.HTMLAttributes<HTMLDocsStylesTableElement>;
            "docs-type-table": LocalJSX.DocsTypeTable & JSXBase.HTMLAttributes<HTMLDocsTypeTableElement>;
            "docs-usage": LocalJSX.DocsUsage & JSXBase.HTMLAttributes<HTMLDocsUsageElement>;
            "es-footer": LocalJSX.EsFooter & JSXBase.HTMLAttributes<HTMLEsFooterElement>;
        }
    }
}
