import type { JsonDocs } from '@stencil/core/internal';

import componentsDocs from '../generated/components';
import editor from '../generated/editor';
import fields from '../generated/fields';

interface Section {
    title: string;
    children: Lib[];
}

interface Lib {
    /*
     * Library short name
     */
    title: string;
    /*
     * Package name on npm
     */
    packageName: string;
    /*
     * url slug
     */
    slug: string;
    /*
     * path to files from repo root
     */
    path: string;
    /*
     * docs generated by stencil
     */
    docs?: JsonDocs;
    /*
     * package.json
     */
    packageJson: PackageJson;
}
interface PackageJson {
    name: string;
    version: string;
    description: string;
    scripts?: Record<string, string>;
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
}

export const sitemap: Section[] = [
    {
        title: 'Web Components',
        children: [
            {
                title: 'Components',
                packageName: '@eventstore/components',
                slug: 'components',
                docs: componentsDocs,
                path: '/packages/components',
                packageJson: await import(
                    '../../packages/components/package.json'
                ),
            },
            {
                title: 'Fields',
                packageName: '@eventstore/fields',
                slug: 'fields',
                docs: fields,
                path: '/packages/fields',
                packageJson: await import('../../packages/fields/package.json'),
            },
            {
                title: 'Router',
                packageName: '@eventstore/router',
                slug: 'router',
                path: '/packages/router',
                packageJson: await import('../../packages/router/package.json'),
            },
            {
                title: 'Editor',
                packageName: '@eventstore/editor',
                slug: 'editor',
                docs: editor,
                path: '/packages/editor',
                packageJson: await import('../../packages/editor/package.json'),
            },
        ],
    },
    {
        title: 'Libraries',
        children: [
            {
                title: 'Utils',
                packageName: '@eventstore/utils',
                slug: 'utils',
                path: '/packages/utils',
                packageJson: await import('../../packages/utils/package.json'),
            },
            {
                title: 'Stores',
                packageName: '@eventstore/stores',
                slug: 'stores',
                path: '/packages/stores',
                packageJson: await import('../../packages/stores/package.json'),
            },
        ],
    },
    {
        title: 'Tools',
        children: [
            {
                title: 'Configs',
                packageName: '@eventstore/configs',
                slug: 'configs',
                path: '/tools/configs',
                packageJson: await import('../../tools/configs/package.json'),
            },
            {
                title: 'Icon Manager',
                packageName: '@eventstore/icon-manager',
                slug: 'icon-manager',
                path: '/tools/icon-manager',
                packageJson: await import(
                    '../../tools/icon-manager/package.json'
                ),
            },
            {
                title: 'Postcss Palette Plugin',
                packageName: '@eventstore/postcss-palette-plugin',
                slug: 'postcss-palette-plugin',
                path: '/tools/postcss-palette-plugin',
                packageJson: await import(
                    '../../tools/postcss-palette-plugin/package.json'
                ),
            },
            {
                title: 'Stencil Markdown Plugin',
                packageName: '@eventstore/stencil-markdown-plugin',
                slug: 'stencil-markdown-plugin',
                path: '/tools/stencil-markdown-plugin',
                packageJson: await import(
                    '../../tools/stencil-markdown-plugin/package.json'
                ),
            },
        ],
    },
];
