/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EsIllustrationBackups {
    }
    interface EsIllustrationBuildingOrgs {
    }
    interface EsIllustrationCloudFolder {
    }
    interface EsIllustrationCluster {
    }
    interface EsIllustrationEsDatabase {
    }
    interface EsIllustrationEvent {
    }
    interface EsIllustrationGroup {
    }
    interface EsIllustrationHarddrive {
    }
    interface EsIllustrationIntegration {
    }
    interface EsIllustrationIssues {
    }
    interface EsIllustrationLaptop {
    }
    interface EsIllustrationNetwork {
    }
    interface EsIllustrationNotifications {
    }
    interface EsIllustrationPeering {
    }
    interface EsIllustrationPendingMember {
    }
    interface EsIllustrationPolicy {
    }
    interface EsIllustrationPoo {
    }
    interface EsIllustrationRainCloud {
    }
    interface EsIllustrationRole {
    }
    interface EsIllustrationScheduledBackups {
    }
    interface EsIllustrationStream {
    }
    interface EsIllustrationToken {
    }
    interface EsIllustrationWelcome {
    }
}
declare global {
    interface HTMLEsIllustrationBackupsElement extends Components.EsIllustrationBackups, HTMLStencilElement {
    }
    var HTMLEsIllustrationBackupsElement: {
        prototype: HTMLEsIllustrationBackupsElement;
        new (): HTMLEsIllustrationBackupsElement;
    };
    interface HTMLEsIllustrationBuildingOrgsElement extends Components.EsIllustrationBuildingOrgs, HTMLStencilElement {
    }
    var HTMLEsIllustrationBuildingOrgsElement: {
        prototype: HTMLEsIllustrationBuildingOrgsElement;
        new (): HTMLEsIllustrationBuildingOrgsElement;
    };
    interface HTMLEsIllustrationCloudFolderElement extends Components.EsIllustrationCloudFolder, HTMLStencilElement {
    }
    var HTMLEsIllustrationCloudFolderElement: {
        prototype: HTMLEsIllustrationCloudFolderElement;
        new (): HTMLEsIllustrationCloudFolderElement;
    };
    interface HTMLEsIllustrationClusterElement extends Components.EsIllustrationCluster, HTMLStencilElement {
    }
    var HTMLEsIllustrationClusterElement: {
        prototype: HTMLEsIllustrationClusterElement;
        new (): HTMLEsIllustrationClusterElement;
    };
    interface HTMLEsIllustrationEsDatabaseElement extends Components.EsIllustrationEsDatabase, HTMLStencilElement {
    }
    var HTMLEsIllustrationEsDatabaseElement: {
        prototype: HTMLEsIllustrationEsDatabaseElement;
        new (): HTMLEsIllustrationEsDatabaseElement;
    };
    interface HTMLEsIllustrationEventElement extends Components.EsIllustrationEvent, HTMLStencilElement {
    }
    var HTMLEsIllustrationEventElement: {
        prototype: HTMLEsIllustrationEventElement;
        new (): HTMLEsIllustrationEventElement;
    };
    interface HTMLEsIllustrationGroupElement extends Components.EsIllustrationGroup, HTMLStencilElement {
    }
    var HTMLEsIllustrationGroupElement: {
        prototype: HTMLEsIllustrationGroupElement;
        new (): HTMLEsIllustrationGroupElement;
    };
    interface HTMLEsIllustrationHarddriveElement extends Components.EsIllustrationHarddrive, HTMLStencilElement {
    }
    var HTMLEsIllustrationHarddriveElement: {
        prototype: HTMLEsIllustrationHarddriveElement;
        new (): HTMLEsIllustrationHarddriveElement;
    };
    interface HTMLEsIllustrationIntegrationElement extends Components.EsIllustrationIntegration, HTMLStencilElement {
    }
    var HTMLEsIllustrationIntegrationElement: {
        prototype: HTMLEsIllustrationIntegrationElement;
        new (): HTMLEsIllustrationIntegrationElement;
    };
    interface HTMLEsIllustrationIssuesElement extends Components.EsIllustrationIssues, HTMLStencilElement {
    }
    var HTMLEsIllustrationIssuesElement: {
        prototype: HTMLEsIllustrationIssuesElement;
        new (): HTMLEsIllustrationIssuesElement;
    };
    interface HTMLEsIllustrationLaptopElement extends Components.EsIllustrationLaptop, HTMLStencilElement {
    }
    var HTMLEsIllustrationLaptopElement: {
        prototype: HTMLEsIllustrationLaptopElement;
        new (): HTMLEsIllustrationLaptopElement;
    };
    interface HTMLEsIllustrationNetworkElement extends Components.EsIllustrationNetwork, HTMLStencilElement {
    }
    var HTMLEsIllustrationNetworkElement: {
        prototype: HTMLEsIllustrationNetworkElement;
        new (): HTMLEsIllustrationNetworkElement;
    };
    interface HTMLEsIllustrationNotificationsElement extends Components.EsIllustrationNotifications, HTMLStencilElement {
    }
    var HTMLEsIllustrationNotificationsElement: {
        prototype: HTMLEsIllustrationNotificationsElement;
        new (): HTMLEsIllustrationNotificationsElement;
    };
    interface HTMLEsIllustrationPeeringElement extends Components.EsIllustrationPeering, HTMLStencilElement {
    }
    var HTMLEsIllustrationPeeringElement: {
        prototype: HTMLEsIllustrationPeeringElement;
        new (): HTMLEsIllustrationPeeringElement;
    };
    interface HTMLEsIllustrationPendingMemberElement extends Components.EsIllustrationPendingMember, HTMLStencilElement {
    }
    var HTMLEsIllustrationPendingMemberElement: {
        prototype: HTMLEsIllustrationPendingMemberElement;
        new (): HTMLEsIllustrationPendingMemberElement;
    };
    interface HTMLEsIllustrationPolicyElement extends Components.EsIllustrationPolicy, HTMLStencilElement {
    }
    var HTMLEsIllustrationPolicyElement: {
        prototype: HTMLEsIllustrationPolicyElement;
        new (): HTMLEsIllustrationPolicyElement;
    };
    interface HTMLEsIllustrationPooElement extends Components.EsIllustrationPoo, HTMLStencilElement {
    }
    var HTMLEsIllustrationPooElement: {
        prototype: HTMLEsIllustrationPooElement;
        new (): HTMLEsIllustrationPooElement;
    };
    interface HTMLEsIllustrationRainCloudElement extends Components.EsIllustrationRainCloud, HTMLStencilElement {
    }
    var HTMLEsIllustrationRainCloudElement: {
        prototype: HTMLEsIllustrationRainCloudElement;
        new (): HTMLEsIllustrationRainCloudElement;
    };
    interface HTMLEsIllustrationRoleElement extends Components.EsIllustrationRole, HTMLStencilElement {
    }
    var HTMLEsIllustrationRoleElement: {
        prototype: HTMLEsIllustrationRoleElement;
        new (): HTMLEsIllustrationRoleElement;
    };
    interface HTMLEsIllustrationScheduledBackupsElement extends Components.EsIllustrationScheduledBackups, HTMLStencilElement {
    }
    var HTMLEsIllustrationScheduledBackupsElement: {
        prototype: HTMLEsIllustrationScheduledBackupsElement;
        new (): HTMLEsIllustrationScheduledBackupsElement;
    };
    interface HTMLEsIllustrationStreamElement extends Components.EsIllustrationStream, HTMLStencilElement {
    }
    var HTMLEsIllustrationStreamElement: {
        prototype: HTMLEsIllustrationStreamElement;
        new (): HTMLEsIllustrationStreamElement;
    };
    interface HTMLEsIllustrationTokenElement extends Components.EsIllustrationToken, HTMLStencilElement {
    }
    var HTMLEsIllustrationTokenElement: {
        prototype: HTMLEsIllustrationTokenElement;
        new (): HTMLEsIllustrationTokenElement;
    };
    interface HTMLEsIllustrationWelcomeElement extends Components.EsIllustrationWelcome, HTMLStencilElement {
    }
    var HTMLEsIllustrationWelcomeElement: {
        prototype: HTMLEsIllustrationWelcomeElement;
        new (): HTMLEsIllustrationWelcomeElement;
    };
    interface HTMLElementTagNameMap {
        "es-illustration-backups": HTMLEsIllustrationBackupsElement;
        "es-illustration-building-orgs": HTMLEsIllustrationBuildingOrgsElement;
        "es-illustration-cloud-folder": HTMLEsIllustrationCloudFolderElement;
        "es-illustration-cluster": HTMLEsIllustrationClusterElement;
        "es-illustration-es-database": HTMLEsIllustrationEsDatabaseElement;
        "es-illustration-event": HTMLEsIllustrationEventElement;
        "es-illustration-group": HTMLEsIllustrationGroupElement;
        "es-illustration-harddrive": HTMLEsIllustrationHarddriveElement;
        "es-illustration-integration": HTMLEsIllustrationIntegrationElement;
        "es-illustration-issues": HTMLEsIllustrationIssuesElement;
        "es-illustration-laptop": HTMLEsIllustrationLaptopElement;
        "es-illustration-network": HTMLEsIllustrationNetworkElement;
        "es-illustration-notifications": HTMLEsIllustrationNotificationsElement;
        "es-illustration-peering": HTMLEsIllustrationPeeringElement;
        "es-illustration-pending-member": HTMLEsIllustrationPendingMemberElement;
        "es-illustration-policy": HTMLEsIllustrationPolicyElement;
        "es-illustration-poo": HTMLEsIllustrationPooElement;
        "es-illustration-rain-cloud": HTMLEsIllustrationRainCloudElement;
        "es-illustration-role": HTMLEsIllustrationRoleElement;
        "es-illustration-scheduled-backups": HTMLEsIllustrationScheduledBackupsElement;
        "es-illustration-stream": HTMLEsIllustrationStreamElement;
        "es-illustration-token": HTMLEsIllustrationTokenElement;
        "es-illustration-welcome": HTMLEsIllustrationWelcomeElement;
    }
}
declare namespace LocalJSX {
    interface EsIllustrationBackups {
    }
    interface EsIllustrationBuildingOrgs {
    }
    interface EsIllustrationCloudFolder {
    }
    interface EsIllustrationCluster {
    }
    interface EsIllustrationEsDatabase {
    }
    interface EsIllustrationEvent {
    }
    interface EsIllustrationGroup {
    }
    interface EsIllustrationHarddrive {
    }
    interface EsIllustrationIntegration {
    }
    interface EsIllustrationIssues {
    }
    interface EsIllustrationLaptop {
    }
    interface EsIllustrationNetwork {
    }
    interface EsIllustrationNotifications {
    }
    interface EsIllustrationPeering {
    }
    interface EsIllustrationPendingMember {
    }
    interface EsIllustrationPolicy {
    }
    interface EsIllustrationPoo {
    }
    interface EsIllustrationRainCloud {
    }
    interface EsIllustrationRole {
    }
    interface EsIllustrationScheduledBackups {
    }
    interface EsIllustrationStream {
    }
    interface EsIllustrationToken {
    }
    interface EsIllustrationWelcome {
    }
    interface IntrinsicElements {
        "es-illustration-backups": EsIllustrationBackups;
        "es-illustration-building-orgs": EsIllustrationBuildingOrgs;
        "es-illustration-cloud-folder": EsIllustrationCloudFolder;
        "es-illustration-cluster": EsIllustrationCluster;
        "es-illustration-es-database": EsIllustrationEsDatabase;
        "es-illustration-event": EsIllustrationEvent;
        "es-illustration-group": EsIllustrationGroup;
        "es-illustration-harddrive": EsIllustrationHarddrive;
        "es-illustration-integration": EsIllustrationIntegration;
        "es-illustration-issues": EsIllustrationIssues;
        "es-illustration-laptop": EsIllustrationLaptop;
        "es-illustration-network": EsIllustrationNetwork;
        "es-illustration-notifications": EsIllustrationNotifications;
        "es-illustration-peering": EsIllustrationPeering;
        "es-illustration-pending-member": EsIllustrationPendingMember;
        "es-illustration-policy": EsIllustrationPolicy;
        "es-illustration-poo": EsIllustrationPoo;
        "es-illustration-rain-cloud": EsIllustrationRainCloud;
        "es-illustration-role": EsIllustrationRole;
        "es-illustration-scheduled-backups": EsIllustrationScheduledBackups;
        "es-illustration-stream": EsIllustrationStream;
        "es-illustration-token": EsIllustrationToken;
        "es-illustration-welcome": EsIllustrationWelcome;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "es-illustration-backups": LocalJSX.EsIllustrationBackups & JSXBase.HTMLAttributes<HTMLEsIllustrationBackupsElement>;
            "es-illustration-building-orgs": LocalJSX.EsIllustrationBuildingOrgs & JSXBase.HTMLAttributes<HTMLEsIllustrationBuildingOrgsElement>;
            "es-illustration-cloud-folder": LocalJSX.EsIllustrationCloudFolder & JSXBase.HTMLAttributes<HTMLEsIllustrationCloudFolderElement>;
            "es-illustration-cluster": LocalJSX.EsIllustrationCluster & JSXBase.HTMLAttributes<HTMLEsIllustrationClusterElement>;
            "es-illustration-es-database": LocalJSX.EsIllustrationEsDatabase & JSXBase.HTMLAttributes<HTMLEsIllustrationEsDatabaseElement>;
            "es-illustration-event": LocalJSX.EsIllustrationEvent & JSXBase.HTMLAttributes<HTMLEsIllustrationEventElement>;
            "es-illustration-group": LocalJSX.EsIllustrationGroup & JSXBase.HTMLAttributes<HTMLEsIllustrationGroupElement>;
            "es-illustration-harddrive": LocalJSX.EsIllustrationHarddrive & JSXBase.HTMLAttributes<HTMLEsIllustrationHarddriveElement>;
            "es-illustration-integration": LocalJSX.EsIllustrationIntegration & JSXBase.HTMLAttributes<HTMLEsIllustrationIntegrationElement>;
            "es-illustration-issues": LocalJSX.EsIllustrationIssues & JSXBase.HTMLAttributes<HTMLEsIllustrationIssuesElement>;
            "es-illustration-laptop": LocalJSX.EsIllustrationLaptop & JSXBase.HTMLAttributes<HTMLEsIllustrationLaptopElement>;
            "es-illustration-network": LocalJSX.EsIllustrationNetwork & JSXBase.HTMLAttributes<HTMLEsIllustrationNetworkElement>;
            "es-illustration-notifications": LocalJSX.EsIllustrationNotifications & JSXBase.HTMLAttributes<HTMLEsIllustrationNotificationsElement>;
            "es-illustration-peering": LocalJSX.EsIllustrationPeering & JSXBase.HTMLAttributes<HTMLEsIllustrationPeeringElement>;
            "es-illustration-pending-member": LocalJSX.EsIllustrationPendingMember & JSXBase.HTMLAttributes<HTMLEsIllustrationPendingMemberElement>;
            "es-illustration-policy": LocalJSX.EsIllustrationPolicy & JSXBase.HTMLAttributes<HTMLEsIllustrationPolicyElement>;
            "es-illustration-poo": LocalJSX.EsIllustrationPoo & JSXBase.HTMLAttributes<HTMLEsIllustrationPooElement>;
            "es-illustration-rain-cloud": LocalJSX.EsIllustrationRainCloud & JSXBase.HTMLAttributes<HTMLEsIllustrationRainCloudElement>;
            "es-illustration-role": LocalJSX.EsIllustrationRole & JSXBase.HTMLAttributes<HTMLEsIllustrationRoleElement>;
            "es-illustration-scheduled-backups": LocalJSX.EsIllustrationScheduledBackups & JSXBase.HTMLAttributes<HTMLEsIllustrationScheduledBackupsElement>;
            "es-illustration-stream": LocalJSX.EsIllustrationStream & JSXBase.HTMLAttributes<HTMLEsIllustrationStreamElement>;
            "es-illustration-token": LocalJSX.EsIllustrationToken & JSXBase.HTMLAttributes<HTMLEsIllustrationTokenElement>;
            "es-illustration-welcome": LocalJSX.EsIllustrationWelcome & JSXBase.HTMLAttributes<HTMLEsIllustrationWelcomeElement>;
        }
    }
}
