/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { editor } from "monaco-editor";
export { editor } from "monaco-editor";
export namespace Components {
    /**
     * Monaco editor wrapped in a web component. Handles re-layout on container resize
     */
    interface EsEditor {
        /**
          * An optional callback for getting a reference to the editor, for external control.
         */
        "editorRef"?: (editor: editor.IStandaloneCodeEditor) => void;
        /**
          * Editor options. see [monaco docs](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandaloneeditorconstructionoptions.html) for details.
         */
        "options": editor.IStandaloneEditorConstructionOptions;
    }
}
declare global {
    /**
     * Monaco editor wrapped in a web component. Handles re-layout on container resize
     */
    interface HTMLEsEditorElement extends Components.EsEditor, HTMLStencilElement {
    }
    var HTMLEsEditorElement: {
        prototype: HTMLEsEditorElement;
        new (): HTMLEsEditorElement;
    };
    interface HTMLElementTagNameMap {
        "es-editor": HTMLEsEditorElement;
    }
}
declare namespace LocalJSX {
    /**
     * Monaco editor wrapped in a web component. Handles re-layout on container resize
     */
    interface EsEditor {
        /**
          * An optional callback for getting a reference to the editor, for external control.
         */
        "editorRef"?: (editor: editor.IStandaloneCodeEditor) => void;
        /**
          * Editor options. see [monaco docs](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandaloneeditorconstructionoptions.html) for details.
         */
        "options"?: editor.IStandaloneEditorConstructionOptions;
    }
    interface IntrinsicElements {
        "es-editor": EsEditor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Monaco editor wrapped in a web component. Handles re-layout on container resize
             */
            "es-editor": LocalJSX.EsEditor & JSXBase.HTMLAttributes<HTMLEsEditorElement>;
        }
    }
}
