/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { editor } from "@kurrent-ui/monaco-editor";
export { editor } from "@kurrent-ui/monaco-editor";
export namespace Components {
    /**
     * Monaco editor wrapped in a web component. Handles re-layout on container resize
     */
    interface E3Editor {
        /**
          * An optional callback for getting a reference to the editor, for external control.
         */
        "editorRef"?: (editor: editor.IStandaloneCodeEditor) => void;
        /**
          * Editor options. see [monaco docs](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandaloneeditorconstructionoptions.html) for details.
         */
        "options": editor.IStandaloneEditorConstructionOptions;
    }
}
declare global {
    /**
     * Monaco editor wrapped in a web component. Handles re-layout on container resize
     */
    interface HTMLE3EditorElement extends Components.E3Editor, HTMLStencilElement {
    }
    var HTMLE3EditorElement: {
        prototype: HTMLE3EditorElement;
        new (): HTMLE3EditorElement;
    };
    interface HTMLElementTagNameMap {
        "e3-editor": HTMLE3EditorElement;
    }
}
declare namespace LocalJSX {
    /**
     * Monaco editor wrapped in a web component. Handles re-layout on container resize
     */
    interface E3Editor {
        /**
          * An optional callback for getting a reference to the editor, for external control.
         */
        "editorRef"?: (editor: editor.IStandaloneCodeEditor) => void;
        /**
          * Editor options. see [monaco docs](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandaloneeditorconstructionoptions.html) for details.
         */
        "options"?: editor.IStandaloneEditorConstructionOptions;
    }
    interface IntrinsicElements {
        "e3-editor": E3Editor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Monaco editor wrapped in a web component. Handles re-layout on container resize
             */
            "e3-editor": LocalJSX.E3Editor & JSXBase.HTMLAttributes<HTMLE3EditorElement>;
        }
    }
}
