/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { editor } from "monaco-editor";
export namespace Components {
    interface EsEditor {
        "editorRef"?: (editor: editor.IStandaloneCodeEditor) => void;
        "options": editor.IStandaloneEditorConstructionOptions;
    }
}
declare global {
    interface HTMLEsEditorElement extends Components.EsEditor, HTMLStencilElement {
    }
    var HTMLEsEditorElement: {
        prototype: HTMLEsEditorElement;
        new (): HTMLEsEditorElement;
    };
    interface HTMLElementTagNameMap {
        "es-editor": HTMLEsEditorElement;
    }
}
declare namespace LocalJSX {
    interface EsEditor {
        "editorRef"?: (editor: editor.IStandaloneCodeEditor) => void;
        "options"?: editor.IStandaloneEditorConstructionOptions;
    }
    interface IntrinsicElements {
        "es-editor": EsEditor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "es-editor": LocalJSX.EsEditor & JSXBase.HTMLAttributes<HTMLEsEditorElement>;
        }
    }
}
