/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DataDemoApp {
    }
    interface ItemList {
    }
    interface SingleItem {
        "itemId": string;
    }
    interface StandardStoreForm {
    }
}
declare global {
    interface HTMLDataDemoAppElement extends Components.DataDemoApp, HTMLStencilElement {
    }
    var HTMLDataDemoAppElement: {
        prototype: HTMLDataDemoAppElement;
        new (): HTMLDataDemoAppElement;
    };
    interface HTMLItemListElement extends Components.ItemList, HTMLStencilElement {
    }
    var HTMLItemListElement: {
        prototype: HTMLItemListElement;
        new (): HTMLItemListElement;
    };
    interface HTMLSingleItemElement extends Components.SingleItem, HTMLStencilElement {
    }
    var HTMLSingleItemElement: {
        prototype: HTMLSingleItemElement;
        new (): HTMLSingleItemElement;
    };
    interface HTMLStandardStoreFormElement extends Components.StandardStoreForm, HTMLStencilElement {
    }
    var HTMLStandardStoreFormElement: {
        prototype: HTMLStandardStoreFormElement;
        new (): HTMLStandardStoreFormElement;
    };
    interface HTMLElementTagNameMap {
        "data-demo-app": HTMLDataDemoAppElement;
        "item-list": HTMLItemListElement;
        "single-item": HTMLSingleItemElement;
        "standard-store-form": HTMLStandardStoreFormElement;
    }
}
declare namespace LocalJSX {
    interface DataDemoApp {
    }
    interface ItemList {
    }
    interface SingleItem {
        "itemId"?: string;
    }
    interface StandardStoreForm {
    }
    interface IntrinsicElements {
        "data-demo-app": DataDemoApp;
        "item-list": ItemList;
        "single-item": SingleItem;
        "standard-store-form": StandardStoreForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "data-demo-app": LocalJSX.DataDemoApp & JSXBase.HTMLAttributes<HTMLDataDemoAppElement>;
            "item-list": LocalJSX.ItemList & JSXBase.HTMLAttributes<HTMLItemListElement>;
            "single-item": LocalJSX.SingleItem & JSXBase.HTMLAttributes<HTMLSingleItemElement>;
            "standard-store-form": LocalJSX.StandardStoreForm & JSXBase.HTMLAttributes<HTMLStandardStoreFormElement>;
        }
    }
}
