name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_call:

jobs:
    build:
        name: 'Build, Test & Lint'
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3

            - name: Cache git lfs
              uses: actions/cache@v3
              with:
                  path: .yarn/cache
                  key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

            - run: git lfs pull

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: '18.x'

            - name: Corepack
              run: corepack enable

            - name: Install
              run: yarn install

            - name: Build
              run: yarn build

            - name: Test
              run: yarn test

            - name: Lint
              run: yarn lint

            - name: Dependencies are deduped
              run: yarn dedupe --check

            - name: All generated code is commited
              run: |
                  git checkout ./.yarn
                  git update-index --refresh
                  git diff-index --exit-code --name-status HEAD --
