name: Release

on:
    push:
        tags:
            - '*'

jobs:
    build-and-test:
        uses: ./.github/workflows/ci.yml
    release:
        runs-on: ubuntu-latest
        needs: [build-and-test]
        steps:
            - uses: actions/checkout@v3

            - name: Cache git lfs
              uses: actions/cache@v3
              with:
                  path: .yarn/cache
                  key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

            - run: git lfs pull

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: '18.x'

            - name: Corepack
              run: corepack enable

            - name: Install
              run: yarn install

            - name: Build
              run: yarn build

            - name: Set access token
              run: yarn config set npmAuthToken "${{ secrets.NPM_AUTH_TOKEN }}"

            - name: publish to npm
              run: yarn workspaces foreach -v --no-private npm publish --access public
